# Generated by Django 4.0.3 on 2022-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_user_product_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
            ],
        ),
    ]
