# Generated by Django 4.0.3 on 2022-03-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_totalarchive'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='totalarchive',
            table='total_archive',
        ),
    ]
