# Generated by Django 4.0.3 on 2022-03-15 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_category_table_alter_product_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='...images'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category'),
        ),
        migrations.AlterField(
            model_name='totalarchive',
            name='total_categories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalarchive',
            name='total_products',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalarchive',
            name='total_users',
            field=models.IntegerField(),
        ),
    ]
